// ------------------------------------------------------------
// Boon Manager
// ------------------------------------------------------------
// What this does (in simple terms):
//   Offers Ancestor boons to players after rooms or shop events.
//   Pulls weighted cards from the appropriate boon decks,
//   charges Scrip based on rarity, and records the choice in state.
//
//   It also exposes chat commands so the GM can manually
//   trigger boon menus or players can confirm their selection.
// ------------------------------------------------------------

var BoonManager = (function () {

  // --- config
  var RARITY_WEIGHTS = { C: 0.45, G: 0.40, S: 0.15 };
  var RARITY_PRICES  = { C: 35,  G: 55,   S: 90   };
  var OFFER_COUNT = 3;

  // --- utilities
  function canonAncestor(name) {
    return (name || '').replace(/[^A-Za-z0-9]/g, '');
  }

  function rarityLabel(r) {
    return r === 'Signature' ? 'Signature' : (r === 'Greater' ? 'Greater' : 'Common');
  }

  function ensureOffers() {
    if (!state.HoardRun) {
      state.HoardRun = {};
    }
    if (!state.HoardRun.boonOffers) {
      state.HoardRun.boonOffers = {};
    }
    return state.HoardRun.boonOffers;
  }

  function getPlayerName(playerid) {
    var p = getObj('player', playerid);
    return p ? '"' + p.get('_displayname') + '"' : '"Unknown"';
  }

  // --- text formatting (escape, then restore **bold**)
  function mdInline(s) {
    if (!s) {
      return '';
    }
    var esc = _.escape(s);
    return esc.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>');
  }

  function ensureListIncludes(list, value) {
    var entries = (list || '').split(',').map(function (v) { return v.trim(); }).filter(Boolean);
    if (entries.indexOf(value) === -1) {
      entries.push(value);
    }
    return entries.join(',');
  }

  function grantHandoutAccess(handout, playerid) {
    if (!handout || !playerid) {
      return;
    }

    var journals = handout.get('inplayerjournals');
    if (journals !== 'all') {
      handout.set('inplayerjournals', ensureListIncludes(journals, playerid));
    }

    var control = handout.get('controlledby');
    if (control !== 'all') {
      handout.set('controlledby', ensureListIncludes(control, playerid));
    }
  }

  function htmlEscape(text) {
    if (!text) {
      return '';
    }
    if (typeof _ !== 'undefined' && _.escape) {
      return _.escape(text);
    }
    return String(text);
  }

  function normalizeDescription(text) {
    if (!text) {
      return '';
    }
    return htmlEscape(text).replace(/\r?\n/g, '<br>');
  }

  function ensureBoonHandout(playerid, card, ancestor) {
    if (!card || !card.name) {
      return;
    }

    var title = card.name;
    var handout = findObjs({ _type: 'handout', name: title })[0];
    if (!handout) {
      handout = createObj('handout', {
        name: title,
        archived: false,
        inplayerjournals: '',
        controlledby: ''
      });
    }

    var rarity = card._rarity || card.rarity || '';
    var description = card.text_in_run || card.description || card.text || '';

    if (description) {
      if (rarity.length === 1) {
        if (rarity === 'C') rarity = 'Common';
        else if (rarity === 'G') rarity = 'Greater';
        else if (rarity === 'S') rarity = 'Signature';
      }
      var rarityText = rarity ? rarityLabel(rarity) : '';
      var parts = [];
      parts.push('<div style="font-family:inherit;font-size:13px;line-height:1.3;">');
      parts.push('<h3 style="margin:0 0 6px 0;">' + htmlEscape(title) + (rarityText ? ' <span style="font-size:11px;font-weight:600;opacity:0.75;">(' + htmlEscape(rarityText) + ')</span>' : '') + '</h3>');
      if (ancestor) {
        parts.push('<div style="font-size:11px;opacity:0.75;margin-bottom:4px;">Ancestor: ' + htmlEscape(ancestor) + '</div>');
      }
      parts.push('<div style="margin-bottom:8px;">' + normalizeDescription(description) + '</div>');
      parts.push('<div style="font-size:10px;opacity:0.6;">Auto-generated by Hoard Run.</div>');
      parts.push('</div>');
      handout.set('notes', parts.join(''));
    }

    grantHandoutAccess(handout, playerid);
  }

  // --- rarity styles (card colors)
  function rarityStyle(r) {
    var map = {
      Common:    { bg: '#0f2d1f', fg: '#e7fff1', br: '#1f6844', badgeBg: '#1aa567' },
      Greater:   { bg: '#0e2140', fg: '#e6f2ff', br: '#1d4e89', badgeBg: '#2a7bdc' },
      Signature: { bg: '#3b2208', fg: '#fff2e0', br: '#7a4513', badgeBg: '#ff8a00' }
    };
    return map[r] || map.Common;
  }

  // --- single boon card
  function cardHTML(c, i) {
    var rarity  = c._rarity || 'Common';
    var style = rarityStyle(rarity);

    var head =
      '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:6px;">' +
        '<div style="font-weight:700;font-size:14px;line-height:1.2;color:' + style.fg + '">' + _.escape(c.name) + '</div>' +
        '<span style="padding:2px 6px;border-radius:6px;font-size:11px;font-weight:700;background:' + style.badgeBg + ';color:#fff;">' +
          _.escape(rarity) +
        '</span>' +
      '</div>';

    var body = '<div style="color:' + style.fg + ';opacity:0.95;line-height:1.25;margin:6px 0 10px 0;">'
             + mdInline(c.text_in_run || '') + '</div>';

    var button = (UIManager && UIManager.buttons)
      ? UIManager.buttons([{ label: 'Choose', command: '!chooseboon ' + i }])
      : '[Choose](!chooseboon ' + i + ')';

    return '<div style="border:1px solid ' + style.br + ';background:' + style.bg + ';padding:10px 10px 12px;border-radius:8px;margin:10px 0;">'
         + head + body + button + '</div>';
  }

  // --- render full offer
  function renderOfferCards(playerName, ancestor, cards, freeMode) {
    var title   = 'Ancestor Boons — ' + _.escape(ancestor);
    var content = cards.map(cardHTML).join('');

    if (!freeMode) {
      content = '<div style="margin-bottom:6px;font-size:11px;opacity:0.85;">Scrip cost applies when you confirm a boon.</div>' + content;
    }

    if (UIManager && UIManager.whisper) {
      // IMPORTANT: do not escape content here; buttons must remain raw.
      UIManager.whisper(playerName, title, content);
      return;
    }

    var shell = (UIManager && UIManager.panel)
      ? UIManager.panel(title, content)
      : '<div style="border:1px solid #444;background:#111;color:#eee;padding:8px;">'
          + '<div style="font-weight:bold;margin-bottom:6px;">' + title + '</div>' + content + '</div>';

    sendChat('Hoard Run', '/w ' + playerName + ' ' + shell);
  }

  // --- weighted draw helpers
  function pickRarity(weights) {
    var roll = Math.random();
    if (roll < weights.C) return 'Common';
    if (roll < weights.C + weights.G) return 'Greater';
    return 'Signature';
  }

  function drawBoons(ancestor) {
    var decksRoot = (state.HoardRun && state.HoardRun.boons) || {};
    var key = canonAncestor(ancestor);
    var deck = decksRoot[key];
    if (!deck) {
      gmSay('⚠️ No boon deck found for "' + ancestor + '" (key: ' + key + ').');
      return [];
    }

    var pools = {
      Common:    (deck.Common    || []).slice(),
      Greater:   (deck.Greater   || []).slice(),
      Signature: (deck.Signature || []).slice()
    };

    var picks = [];
    for (var i = 0; i < OFFER_COUNT; i++) {
      var preferred = pickRarity(RARITY_WEIGHTS);
      var order = preferred === 'Common' ? ['Common', 'Greater', 'Signature']
                : preferred === 'Greater' ? ['Greater', 'Common', 'Signature']
                : ['Signature', 'Greater', 'Common'];

      var chosen = null;
      for (var j = 0; j < order.length; j++) {
        var pool = pools[order[j]];
        if (pool && pool.length) {
          var idx = Math.floor(Math.random() * pool.length);
          chosen = pool.splice(idx, 1)[0];
          chosen._rarity = order[j];
          chosen._idx = picks.length;
          break;
        }
      }

      if (!chosen) {
        break;
      }
      picks.push(chosen);
    }

    return picks;
  }

  // --- public actions
  /** Offers boon choices to the specified player */
  function offerBoons(playerid, ancestorArg, modeArg) {
    StateManager.initPlayer(playerid);

    var ps = StateManager.getPlayer(playerid) || {};
    var chosenAncestor = ancestorArg && ancestorArg.trim()
      ? ancestorArg.replace(/_/g, ' ')
      : (ps.ancestor_id || (state.HoardRun && state.HoardRun.runFlow && state.HoardRun.runFlow.ancestor) || 'Azuren');

    var freeMode = true; // end-of-room default
    if (typeof modeArg === 'string') {
      var m = modeArg.toLowerCase();
      if (m === 'shop' || m === 'paid' || m === 'cost') {
        freeMode = false;
      }
    }

    var cards = drawBoons(chosenAncestor);
    if (!cards.length) {
      gmSay('⚠️ No boon cards were drawn for ' + canonAncestor(chosenAncestor) + '.');
      return;
    }

    ensureOffers()[playerid] = { ancestor: chosenAncestor, free: freeMode, cards: cards };
    renderOfferCards(getPlayerName(playerid), chosenAncestor, cards, freeMode);
  }

  /** Handles the player selecting a boon */
  function chooseBoon(playerid, choiceIdx) {
    var offers = ensureOffers();
    var offer = offers[playerid];
    var index = parseInt(choiceIdx, 10);

    if (!offer || !offer.cards || isNaN(index) || index < 0 || index >= offer.cards.length) {
      gmSay('BoonManager: No active boon offer for you, or invalid choice.');
      return;
    }

    var picked = offer.cards[index];
    var rarity = picked._rarity || 'Common';
    var cost = offer.free ? 0 : (RARITY_PRICES[rarity === 'Signature' ? 'S' : (rarity === 'Greater' ? 'G' : 'C')] || 0);

    if (cost > 0 && !StateManager.spendScrip(playerid, cost)) {
      return;
    }

    var ps = StateManager.getPlayer(playerid);
    if (!ps.boons) {
      ps.boons = [];
    }
    ps.boons.push({
      id: picked.id || picked.name,
      name: picked.name,
      rarity: rarity,
      ancestor: offer.ancestor,
      acquiredAt: new Date().toISOString(),
      cost: cost
    });

    delete offers[playerid];

    ensureBoonHandout(playerid, picked, offer.ancestor);

    var playerName = getPlayerName(playerid);
    var message = '🌟 You gained <b>' + _.escape(picked.name) + '</b> (' + rarityLabel(rarity) + ')'
                + (cost > 0 ? (' for ' + cost + ' Scrip!') : ' for 0 Scrip (free reward).');

    if (UIManager && UIManager.whisper) {
      UIManager.whisper(playerName, 'Boon Gained', message);
    } else {
      whisperRaw(playerName, message);
    }
  }

  // --- chat commands
  /** Chat command dispatcher */
  function handleChat(msg) {
    if (msg.type !== 'api') {
      return;
    }
    var parts = msg.content.trim().split(/\s+/);
    var command = parts.shift();

    if (command === '!offerboons') {
      var ancestor = parts[0];
      var modeFlag = parts[1] || 'free';
      offerBoons(msg.playerid, ancestor, modeFlag);
    }
    if (command === '!chooseboon') {
      chooseBoon(msg.playerid, parts[0]);
    }
  }

  /** Registers chat listeners */
  function register() {
    on('chat:message', handleChat);
  }

  return {
    offerBoons: offerBoons,
    chooseBoon: chooseBoon,
    register: register
  };

})();

function gmSay(msg) {
  var payload = '/w gm ' + msg;
  if (typeof HRChat !== 'undefined' && HRChat && typeof HRChat.say === 'function') {
    HRChat.say(payload);
  } else {
    sendChat('Hoard Run', payload);
  }
}

function whisperRaw(target, msg) {
  var payload = '/w ' + target + ' ' + msg;
  if (typeof HRChat !== 'undefined' && HRChat && typeof HRChat.say === 'function') {
    HRChat.say(payload);
  } else {
    sendChat('Hoard Run', payload);
  }
}

